doh.registerUrl("simple", "../simple.html");
doh.registerUrl("config", "../config.html");
doh.registerUrl("simple-nohead", "../simple-nohead.html");
doh.registerUrl("circular", "../circular.html");
doh.registerUrl("depoverlap", "../depoverlap.html");
doh.registerUrl("multiversion", "../multiversion.html", 10000);
doh.registerUrl("jquery", "../jquery/jquery.html");
doh.registerUrl("i18nlocaleunknown", "../i18n/i18n.html?bundle=i18n!nls/fr-fr/colors");
doh.registerUrl("i18n", "../i18n/i18n.html");
doh.registerUrl("i18nlocale", "../i18n/i18n.html?locale=en-us-surfer");
doh.registerUrl("i18nbundle", "../i18n/i18n.html?bundle=i18n!nls/en-us-surfer/colors");
doh.registerUrl("modifiers", "../modifier/modifier.html", 10000);
doh.registerUrl("pause/resume", "../pauseresume/pauseresume.html", 10000);
doh.registerUrl("afterload", "../afterload.html", 10000);
doh.registerUrl("text", "../text/text.html");
doh.registerUrl("relative", "../relative/relative.html");
