doh.registerUrl("simple", "../simple.html");
doh.registerUrl("simple-nohead", "../simple-nohead.html");
doh.registerUrl("circular", "../circular.html");
doh.registerUrl("depoverlap", "../depoverlap.html");
doh.registerUrl("urlfetch", "../urlfetch/urlfetch.html");
doh.registerUrl("pause/resume", "../pauseresume/pauseresume.html", 10000);
doh.registerUrl("jquery", "../jquery/jquery.html");
doh.registerUrl("relative", "../relative/relative.html");
doh.registerUrl("priority", "../priority/priority.html");
doh.registerUrl("prioritySingleCall", "../priority/prioritySingleCall.html");
